### ISSUE TITLE
letra agradable no bulling

### ISSUE THREAD

**Issue by pedrobernal1579442** [pedrobernal1579442/PercepcionN6Equipo-9#3]
en el verso 2 renglón 8 hay una palabra que no se si puede afectar con personas por lo que dice la palabra es "fea" que sugieren para cambiar por otra palabra?

**Comment by EduRamirez** [comment]
Creo que la palabra podria ser bella amigo

**Comment by pedrobernal1579442** [comment]
fixes #5
